### ISSUE TITLE
The python file shows this error while running

### ISSUE THREAD

**Issue by Siddharth1698** [Karlheinzniebuhr/torshammer#1]
File "torshammer.py", line 76
    print term.BOL+term.UP+term.CLEAR_EOL+"Posting: %s" % p+term.NORMAL
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(term.BOL+term.UP+term.CLEAR_EOL+"Posting: %s" % p+term.NORMAL)?

**Comment by LennyPhoenix** [comment]
Make sure you are using python 2.7 to run it.

**Comment by Karlheinzniebuhr** [comment]
Just updated it for python 3, could you try again now ?
